#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    PowerExpander,  sensorAnalog)
#pragma config(Sensor, dgtl1,  Brake1,         sensorDigitalOut)
#pragma config(Sensor, dgtl2,  Brake2,         sensorDigitalOut)
#pragma config(Sensor, dgtl3,  collection_encoder, sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  encoder_left,   sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  encoder_right,  sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           CollectB,      tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           LeftB,         tmotorVex393_MC29, PIDControl, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port3,           RightB,        tmotorVex393_MC29, PIDControl, encoderPort, I2C_4)
#pragma config(Motor,  port4,           LeftA,         tmotorVex393_MC29, PIDControl, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port5,           RightA,        tmotorVex393_MC29, PIDControl, encoderPort, I2C_3)
#pragma config(Motor,  port6,           DriveRearLeft, tmotorVex393HighSpeed_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port7,           DriveRearRight, tmotorVex393HighSpeed_MC29, openLoop, driveRight)
#pragma config(Motor,  port8,           DriveFrontLeft, tmotorVex393HighSpeed_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port9,           DriveFrontRight, tmotorVex393HighSpeed_MC29, openLoop, driveRight)
#pragma config(Motor,  port10,          CollectA,      tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// TO CHANGE LCD THING, GO TO LCD FILE LINE: 272
#define NoLiftLimits
#define NoDriveEncoder
#define OneLiftEncoder
//#define NoPowerExpander
//#define MultiDriveEncoders.
#if defined(_DEBUG)
const string FILE = __FILE__;
#endif

#include "core/v1/core.h"
//#include "core/misc/2105.func.h"

void autonFunc(){
	clearTimer(T1);
	while(time1[T1] <= 15){
		SensorValue[Brake1] = 1;
		SensorValue[Brake2] = 1;
		Auton_Launch(127);
		sleep(3000);
		int count = 0;
		SensorValue[collection_encoder] = 0;
		while(count < 4){
			if(count < 1){
				Auton_Launch(127);
			}else{
				Auton_Launch(108);
			}
			SensorValue[collection_encoder] = 0;
			while(SensorValue[collection_encoder] < 660){
				Auton_Collect(127);
			}
			Auton_Collect(0, 650);
			SensorValue[collection_encoder] = 0;
			if(count <= 4){
				while(SensorValue(collection_encoder) <= 210){
					Auton_Collect(127);
				}
			}
			count++;
		}
		allMotorsOff();
	}
	allMotorsOff();
}
task launchSound(){
	while(true){
		playSound(soundFastUpwardTones);
		wait1Msec(1750);
	}
}
#include "core/DriverProfiles/2105A.h"
#include "core/auton/2105A-blue-left.h"
#include "core/auton/2105A-blue-right.h"
#include "core/auton/2105A-red-left.h"
#include "core/auton/2105A-red-right.h"
//#include "core/auton/2105A-Progskills.h"
#include "core/misc/2105A-autonmanager.h"

void ResetDriveEncoders() {
	nMotorEncoder[LeftA] = 0;
	nMotorEncoder[RightA] = 0;
	nMotorEncoder[LeftB] = 0;
	nMotorEncoder[RightB] = 0;
	SensorValue[collection_encoder] = 0;
	SensorValue[Brake1] = 0;
	SensorValue[Brake2] = 0;

}

void init() {
	ResetDriveEncoders();
}
