#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    PowerExpander,  sensorAnalog)
#pragma config(Sensor, dgtl1,  Brake1,         sensorDigitalOut)
#pragma config(Sensor, dgtl2,  Brake2,         sensorDigitalOut)
#pragma config(Sensor, dgtl3,  collection_encoder, sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  encoder_leftB,  sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  encoder_leftA,  sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  encoder_rightA, sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  encoder_rightB, sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           CollectionB,   tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           LeftB,         tmotorVex393_MC29, PIDControl, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port3,           RightB,        tmotorVex393_MC29, PIDControl, encoderPort, I2C_4)
#pragma config(Motor,  port4,           LeftA,         tmotorVex393_MC29, PIDControl, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port5,           RightA,        tmotorVex393_MC29, PIDControl, encoderPort, I2C_3)
#pragma config(Motor,  port6,           DriveRearLeft, tmotorVex393HighSpeed_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port7,           DriveRearRight, tmotorVex393HighSpeed_MC29, openLoop, driveRight)
#pragma config(Motor,  port8,           DriveFrontLeft, tmotorVex393HighSpeed_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port9,           DriveFrontRight, tmotorVex393HighSpeed_MC29, openLoop, driveRight)
#pragma config(Motor,  port10,          CollectionA,   tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Update inteval (in mS) for the flywheel control loop
#define FWL_LOOP_SPEED              25

// Maximum power we want to send to the flywheel motors
#define FWL_MAX_POWER              127

// encoder counts per revolution depending on motor
#define MOTOR_TPR_269           240.448
#define MOTOR_TPR_393R          261.333
#define MOTOR_TPR_393S          392
#define MOTOR_TPR_393T          627.2
#define MOTOR_TPR_QUAD          360.0

// Structure to gather all the flywheel ralated data
typedef struct _fwL_controller {
	long            counter;                ///< loop counter used for debug

	// encoder tick per revolution
	float           ticks_per_rev;          ///< encoder ticks per revolution

	// Encoder
	long            e_current;              ///< current encoder count
	long            e_last;                 ///< current encoder count

	// velocity measurement
	float           v_current;              ///< current velocity in rpm
	long            v_time;                 ///< Time of last velocity calculation

	// TBH control algorithm variables
	long            target;                 ///< target velocity
	long            current;                ///< current velocity
	long            last;                   ///< last velocity
	float           error;                  ///< error between actual and target velocities
	float           last_error;             ///< error last time update called
	float           gain;                   ///< gain
	float           drive;                  ///< final drive out of TBH (0.0 to 1.0)
	float           drive_at_zero;          ///< drive at last zero crossing
	long            first_cross;            ///< flag indicating first zero crossing
	float           drive_approx;           ///< estimated open loop drive

	// final motor drive
	long            motor_drive;            ///< final motor control value
} fwL_controller;

// Make the controller global for easy debugging
static  fwL_controller   flywheel;

/*-----------------------------------------------------------------------------*/
/** @brief      Set the flywheen motors                                        */
/** @param[in]  value motor control value                                      */
/*-----------------------------------------------------------------------------*/
void
FwLMotorSet( int motorSpeed )
{
	motor[LeftB] = motorSpeed;
	//motor[RightB] = motorSpeed;
	motor[LeftA] = motorSpeed;
	//motor[RightA] = motorSpeed;
}

/*-----------------------------------------------------------------------------*/
/** @brief      Get the flywheen motor encoder count                           */
/*-----------------------------------------------------------------------------*/
long
FwLMotorEncoderGet()
{
	return( (abs(nMotorEncoder[LeftA])) * 49/3 );
}

/*-----------------------------------------------------------------------------*/
/** @brief      Set the controller position                                    */
/** @param[in]  fw pointer to flywheel controller structure                    */
/** @param[in]  desired velocity                                               */
/** @param[in]  predicted_drive estimated open loop motor drive                */
/*-----------------------------------------------------------------------------*/
void
FwLVelocitySet( fwL_controller *fwL, int velocity, float predicted_drive )
{
	// set target velocity (motor rpm)
	fwL->target        = velocity;

	// Set error so zero crossing is correctly detected
	fwL->error         = fwL->target - fwL->current;
	fwL->last_error    = fwL->error;

	// Set predicted open loop drive value
	fwL->drive_approx  = predicted_drive;
	// Set flag to detect first zero crossing
	fwL->first_cross   = 1;
	// clear tbh variable
	fwL->drive_at_zero = 0;
}

/*-----------------------------------------------------------------------------*/
/** @brief      Calculate the current flywheel motor velocity                  */
/** @param[in]  fw pointer to flywheel controller structure                    */
/*-----------------------------------------------------------------------------*/
void
FwLCalculateSpeed( fwL_controller *fwL )
{
	int     delta_ms;
	int     delta_enc;

	// Get current encoder value
	fwL->e_current = FwLMotorEncoderGet();

	// This is just used so we don't need to know how often we are called
	// how many mS since we were last here
	delta_ms   = nSysTime - fwL->v_time;
	fwL->v_time = nSysTime;

	// Change in encoder count
	delta_enc = (fwL->e_current - fwL->e_last);

	// save last position
	fwL->e_last = fwL->e_current;

	// Calculate velocity in rpm
	fwL->v_current = (1000.0 / delta_ms) * delta_enc * 60.0 / fwL->ticks_per_rev;
}

/*-----------------------------------------------------------------------------*/
/** @brief      Update the velocity tbh controller variables                   */
/** @param[in]  fw pointer to flywheel controller structure                    */
/*-----------------------------------------------------------------------------*/
void
FwLControlUpdateVelocityTbh( fwL_controller *fwL )
{
	// calculate error in velocity
	// target is desired velocity
	// current is measured velocity
	fwL->error = fwL->target - fwL->current;

	// Use Kp as gain
	fwL->drive =  fwL->drive + (fwL->error * fwL->gain);

	// Clip - we are only going forwards
	if( fwL->drive > 1 )
		fwL->drive = 1;
	if( fwL->drive < 0 )
		fwL->drive = 0;

	// Check for zero crossing
	if( sgn(fwL->error) != sgn(fwL->last_error) ) {
		// First zero crossing after a new set velocity command
		if( fwL->first_cross ) {
			// Set drive to the open loop approximation
			fwL->drive = fwL->drive_approx;
			fwL->first_cross = 0;
		}
		else
			fwL->drive = 0.55 * ( fwL->drive + fwL->drive_at_zero ); // ORIG 0.5

		// Save this drive value in the "tbh" variable
		fwL->drive_at_zero = fwL->drive;
	}

	// Save last error
	fwL->last_error = fwL->error;
}

/*-----------------------------------------------------------------------------*/
/** @brief     Task to control the velocity of the flywheel                    */
/*-----------------------------------------------------------------------------*/
task
FwLControlTask()
{
	fwL_controller *fwL = &flywheel;

	// Set the gain
	fwL->gain = 0.00025;

	// We are using Speed geared motors
	// Set the encoder ticks per revolution
	fwL->ticks_per_rev = MOTOR_TPR_393S;

	while(1)
	{
		// debug counter
		fwL->counter++;

		// Calculate velocity
		FwLCalculateSpeed( fwL );

		// Set current speed for the tbh calculation code
		fwL->current = fwL->v_current;

		// Do the velocity TBH calculations
		FwLControlUpdateVelocityTbh( fwL ) ;

		// Scale drive into the range the motors need
		fwL->motor_drive  = (fwL->drive * FWL_MAX_POWER) + 0.55; // Orig: 0.5

		// Final Limit of motor values - don't really need this
		if( fwL->motor_drive >  127 ) fwL->motor_drive =  127;
		if( fwL->motor_drive < -127 ) fwL->motor_drive = -127;

		// and finally set the motor control value
		FwLMotorSet( fwL->motor_drive );

		// Run at somewhere between 20 and 50mS
		wait1Msec( FWL_LOOP_SPEED );
	}
}




// Main user task
task main()
{
	// Line 211

	char  str[32];

	bLCDBacklight = true;

	// Start the flywheel control task
	startTask( FwLControlTask );
	nMotorEncoder[encoder_leftA] = 0;
	// Main user control loop

	//startTask( Collect );

	while(1)
	{
		// Different speeds set by buttons
		if( vexRT[ Btn8L ] == 1 )
			FwLVelocitySet( &flywheel, 2325, 0.7 ); //2500 norm
		if( vexRT[ Btn8U ] == 1 )
			FwLVelocitySet( &flywheel, 120, 0.38 );
		if( vexRT[ Btn8R ] == 1 )
			FwLVelocitySet( &flywheel, 50, 0.2 );
		if( vexRT[ Btn8D ] == 1 )
			FwLVelocitySet( &flywheel, 00, 0 );

		/*
		if(vexRT[Btn6U] == 1){
		motor[CollectionA] =  127;
		motor[CollectionB] =  127;
		}else if(vexRT[Btn6D] == 1){
		motor[CollectionA] =  -127;
		motor[CollectionB] =  -127;
		}else{
		motor[CollectionA] = 127;
		motor[CollectionB] =  127;
		}*/

		// Display useful things on the LCD
		sprintf( str, "%4d %4d  %5.2f", flywheel.target,  flywheel.current, nImmediateBatteryLevel/1000.0 );
		displayLCDString(0, 0, str );
		sprintf( str, "%4.2f %4.2f ", flywheel.drive, flywheel.drive_at_zero );
		displayLCDString(1, 0, str );

		// Don't hog the cpu :)
		wait1Msec(10);
	}

}
